### ISSUE TITLE
Small typo in the docs

### ISSUE THREAD

**Issue by tcjansen** [mwvgroup/pwv_kpno#29]
In [Installation and Setup](https://mwvgroup.github.io/pwv_kpno/1.0.0/documentation/html/install.html), section 1.2, there's an extra `settings` in line 8 of the example code:

```
 >>> from pwv_kpno.package_settings import settings
 >>>
 >>> sites_to_backup = settings.available_sites
 >>> general_path = './site_backups/{}.ecsv'
 >>> for site in sites_to_backup:
 >>>     settings.set_site(site)
 >>>     out_path = general_path.format(site)
 >>>     settings.settings.export_site_config(out_path)
```
which returns `AttributeError: 'Settings' object has no attribute 'settings'`. Just thought I'd let you know! :)

**Comment by djperrefort** [comment]
Fixed it. Thanks for the heads up!!
