### ISSUE TITLE
Convenience function to return PWV for array of MJD[, airmass]

### ISSUE THREAD

**Issue by wmwv** [mwvgroup/pwv_kpno#31]
**Is your feature request related to a problem? Please describe.**
I'd like to use pwv_kpno to match to a specific observation.  I generally have observations in MJD.

**Describe the solution you'd like**
I'd like to be able to retrieve an array of PWV values from an array of MJDs for a given site.  If an array of airmass values of the same size as MJD is given, then apply those airmass corrections.

**Describe alternatives you've considered**
This can currently be done by converting the list of MJDs to datetime objects.

```
from astropy.time import Time
times = Time(mjd_obs, format='mjd')
datetimes = times.to_datetime()

pwv_values = [pwv_atm.pwv_date(dt) for dt in datetimes]
```
But that's a little awkward and ends up with a list of tuples instead of a table.  It would be nice to not have to convert externally.  And it would be nice to be able to just pass the array instead of looping.

**Comment by wmwv** [comment]
```
Table(rows=pwv_values, names=('pwv', 'pwv_err'), dtype=(np.float, np.float))
```

would create a table.

**Comment by djperrefort** [comment]
@wmwv If you install from master you can now do:

```python
from pwv_kpno.pwv_atm import pwv_date 

unix_times = [1292112000.0, 1292284800.0]
pwv_array, err_array = pwv_date(unix_times, format='unix')

mjd_times = [55542.0, 55544.0]
pwv_array, err_array = pwv_date(mjd_times, format='mjd')
```

**Comment by wmwv** [comment]
Is there a new test associated with this new functionality?

**Comment by djperrefort** [comment]
No - I didn't have the time to add a new test, but I definitely should/will.
