### ISSUE TITLE
Memory usage grows to 100s of GB when calculating 100,000s of dates with `pwv_date`

### ISSUE THREAD

**Issue by wmwv** [mwvgroup/pwv_kpno#35]
**Describe the bug**
When calculating large numbers of dates, the memory used grows without bound.
It was at 100s of GB when my laptop crawled to a halt, filled up disk with swap space.

Running more carefully and monitoring I see that it quickly builds up to 10s of GB.

**To Reproduce**
The following snippet, run at N=1000 builds to 3.7 GB of memory; (N=100, mem=200 MB; N=2000, mem=7.8 GB)
```
import os
import numpy as np
from pwv_kpno import pwv_atm

N = 1000
mjd_obs = np.linspace(57500, 58200, N)
pwv, pwv_err = pwv_atm.pwv_date(mjd_obs, format='mjd')
```

**Expected behavior**
Expectation is that memory usage should grow to no more than a few hundred MB
even when calculating 600,000 rows.

**Version**
v 1.2.0 as downloaded through `pip`.  Python 3.7.  numpy 1.18.1.

**Comment by wmwv** [comment]
I've isolated it down to the `_warn_available_data(time_stamp, pwv_model['date'])`
That's the line that's responsible for this memory growth.

**Comment by wmwv** [comment]
differences = (test_dates.reshape(1, -1) - known_dates.reshape(-1, 1))
    indices = np.abs(differences).argmin(axis=0)
    residual = np.diagonal(differences[indices,])

**Comment by wmwv** [comment]
This is where the memory is being taken up.
`differences` has shape `(len(known_dates), len(test_dates))`

Then `np.abs` has to create a second temporary matrix of that same size.

**Comment by wmwv** [comment]
168,689 * 600,000 is a very big number...

**Comment by wmwv** [comment]
Think a little more about this, there are two things to address.
1. Picking a less memory intensive way to find the closest match.
2. Deciding what to do if 1 entry out of, e.g., 100 requested falls outside of range.  Raising `ValueError` is possibly no longer the right thing to do when supporting arrays of input dates.

**Comment by djperrefort** [comment]
I'll take a look at optimizing this. 

In general, there are a few places in the package that could use some optimization, and me having written the package before knowing OOD or Pandas resulted in some inefficiencies. I'll focus on this issue first since it effects our progress on the MZLS work, but I'll also mentally flag this as a reminder to implement some other improvements in the near future that have been floating around my head.
